services:
  - type: web
    name: wordpress
    env: docker
    repo: https://github.com/mmmihaeel/realtydemo
    branch: main
    dockerContext: docker
    dockerfilePath: Dockerfiles/WordPress.Dockerfile
    autoDeploy: true
    envVars:
      - key: WORDPRESS_DB_HOST
        value: database:3306
      - key: WORDPRESS_DB_NAME
        value: ${MYSQL_DATABASE}
      - key: WORDPRESS_DB_USER
        value: ${MYSQL_USER}
      - key: WORDPRESS_DB_PASSWORD
        value: ${MYSQL_PASSWORD}
    plan: free

  - type: pserv
    name: database
    env: docker
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO
    branch: main
    dockerContext: docker
    autoDeploy: false
    plan: free
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: ${MYSQL_ROOT_PASSWORD}
      - key: MYSQL_DATABASE
        value: ${MYSQL_DATABASE}
      - key: MYSQL_USER
        value: ${MYSQL_USER}
      - key: MYSQL_PASSWORD
        value: ${MYSQL_PASSWORD}
