services:
  - type: web
    name: wordpress-app
    env: docker
    dockerfilePath: Dockerfiles/WordPress.Dockerfile
    dockerContext: .
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: WORDPRESS_DB_HOST
        value: dpg-d09u1sodl3ps7392spbg-a:5432
      - key: WORDPRESS_DB_NAME
        value: realtydemo_database
      - key: WORDPRESS_DB_USER
        value: realtydemo
      - key: WORDPRESS_DB_PASSWORD
        value: dpg-d09u1sodl3ps7392spbg-a
    plan: free
